# Generated by Django 5.2.7 on 2025-11-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_ordritem_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.TextField(max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(),
        ),
    ]
