# Generated by Django 5.2.8 on 2026-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('momo', 'Momo Pay'), ('airtel', 'Airtel Money')], default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
