# Generated by Django 5.2.8 on 2026-01-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_purchase_payment_method_purchase_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
