# Generated by Django 5.2.8 on 2026-01-29 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_delivery_cost_order_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.18, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
