# Generated by Django 5.2.8 on 2025-12-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_update_tomatoes_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg'), ('stick', 'stick'), ('bundle', 'bundle')], default='pcs', max_length=20),
        ),
    ]
