# Generated by Django 6.0.1 on 2026-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('meter', 'Meter (m)'), ('sqm', 'Square Meter (m²)'), ('cbm', 'Cubic Meter (m³)'), ('bundle', 'Bundle'), ('set', 'Set')], default='pcs', max_length=20),
        ),
    ]
