# Generated by Django 6.0.1 on 2026-01-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('meter', ' Per Meter (m)'), ('sqm', 'per Square Meter (m²)')], default='meter', max_length=20),
        ),
    ]
