# Generated by Django 5.2.8 on 2026-01-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bed', 'Bed'), ('chair', 'Chair'), ('table', 'Table'), ('kitchen_tools', 'Kitchen Tools'), ('artisan_designer', 'Artisan / Wooden Designer'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
