# Generated by Django 5.2.8 on 2026-01-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', help_text='Enter measurement unit (e.g., pcs, meter, sqm, kg, bundle, etc.)', max_length=50),
        ),
    ]
