# Generated by Django 5.2.8 on 2026-01-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_update_unit_field_to_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('home_office', 'Home & Office'), ('outdoor_garden', 'Outdoor & Garden'), ('doors_construction', 'Doors & Construction'), ('handcrafted', 'Handcrafted Products'), ('custom_made', 'Custom Made'), ('raw_materials', 'Raw Materials'), ('kids_school', 'Kids & School'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
